### ISSUE TITLE
high severity vulnerabilities - advanced-2020-master

### ISSUE THREAD

**Issue by MARS-GHub** [john-smilga/react-advanced-2020#3]
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.6.5 postinstall /Users/m***/Desktop/reactApp/react-advanced-2020-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.6.5 postinstall /Users/m***/Desktop/reactApp/react-advanced-2020-master/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

added 1638 packages from 798 contributors and audited 1638 packages in 17.264s

67 packages are looking for funding
  run `npm fund` for details

found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details`

**Comment by mrinalsarkar1999** [comment]
Same error. I tried npm audit fix and force fix too but it didn't help. Also the project wont deploy/start. "npm start" throws an error at event.js.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tutorial@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tutorial@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mrina\AppData\Roaming\npm-cache\_logs\2020-12-22T13_37_05_882Z-debug.log

**Comment by Ravindrayadavrk1006** [comment]
@mrinalsarkar1999  
follow the following steps :
1. delete node_modules folder
2. delete package-lock.json
3. initiate command : npm install && npm start

**Comment by victornguyen75** [comment]
Ravindrayadavrk1006's suggestion works. @john-smilga, would you like me to create a pull request to fix the package.json and package-lock.json files?
